### PR TITLE
Bump to v0.13.1

### PR DESCRIPTION
**Pull request by nick-harmening**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nick-harmening** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
Can you add yourself as a maintainer in this PR?

**Comment by xhochy** [comment]
Also please fix the lint.

**Comment by nick-harmening** [comment]
@conda-forge-admin, please lint

**Comment by nick-harmening** [comment]
@xhochy, thank you for the review, please check again.

**Review by xhochy — APPROVED** [review]

**Pull request merged**
